# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       [ROLE_USER,ROLE_MANAGER]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,                      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,                   role: ROLE_NONE }
        - { path: ^/manager,                     role: ROLE_ADMIN }
        - { path: ^/member,                        role: ROLE_USER }
        - { path: ^/,                            role: IS_AUTHENTICATED_ANONYMOUSLY }

